package org.icddrb.dhis.android.sdk.persistence.preferences;

public enum ResourceType {
    DASHBOARDS_CONTENT,
    DASHBOARDS,
    INTERPRETATIONS,
    USERS,
    OPTIONSETS,
    PROGRAMS,
    PROGRAM,
    TRACKEDENTITYATTRIBUTES,
    CONSTANTS,
    ASSIGNEDPROGRAMS,
    PROGRAMRULES,
    PROGRAMRULEVARIABLES,
    PROGRAMRULEACTIONS,
    RELATIONSHIPTYPES,
    EVENTS,
    EVENT,
    TRACKEDENTITYINSTANCE,
    ENROLLMENT,
    ENROLLMENTS,
    TRACKEDENTITYATTRIBUTEGENERATEDVALUES,
    TRACKEDENTITYATTRIBUTEGROUPS
}
